<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Document sans titre</title>
<style type="text/css">
<!--
body {
	background-image: url(WhatsApp Image 2024-01-18 à 13.28.37_12ec6847.jpg);
	background-image: url(WhatsApp%20Image%202024-01-18%20%C3%A0%2013.28.37_12ec6847.jpg);
}
.Style6 {color: #CA5631; font-size: 18px; }
.Style12 {font-size: 36px; font-family: Arial, Helvetica, sans-serif; color: #571C16;}
.Style13 {color: #86665B}
.Style15 {font-size: 12}
.Style17 {font-size: 24px}
.Style18 {font-family: "Courier New", Courier, monospace}
.Style19 {font-size: 24px; font-family: "Courier New", Courier, monospace; }
.Style21 {
	color: #FFFFFF;
	font-family: Georgia, "Times New Roman", Times, serif;
	font-weight: bold;
}
.Style22 {color: #FFFFFF}
.Style24 {color: #FFFFFF; font-weight: bold; }
.Style30 {font-size: 18px}
.Style31 {font-weight: bold; font-family: "Courier New", Courier, monospace;}
.Style32 {color: #C34F28; font-style: italic; font-family: "Courier New", Courier, monospace;}
.Style33 {color: #CED8DA; background-color: #CA5631; font-family: "Courier New", Courier, monospace;}
.Style34 {
	font-size: 18px;
	color: #FFFFFF;
	font-family: Georgia, "Times New Roman", Times, serif;
}
-->
</style>
</head>

<body>
<form action="" method="post" name="form1" class="Style30" id="form1">
  <div align="center" class="Style31">
    <div align="left" class="Style32">IDEAL MARKET  </div>
  </div>
</form>
<form action="" method="post" name="form2" class="Style30" id="form2">
  <p align="center" class="Style33">BIENVENUE DANS NOTRE PAGE IDEAL MARKET </p>
</form>
<p class="Style30">&nbsp;</p>
<form id="form3" name="form3" method="post" action="">
  <div align="center">
    <table width="739" border="1">
      <tr bgcolor="#000000">
        <td class="Style6">CLIENTS</td>
        <td class="Style6">COMMANDES</td>
        <td class="Style6">EMPLOYES</td>
        <td class="Style6">PRODUITS</td>
        <td class="Style6">RAYONS</td>
      </tr>
      <tr>
        <td height="102"><div align="left">
          <p class="Style34">NOU<strong>S PERMET DE SAVOIR DES INFORMATION SUR L</strong>E CLEINT </p>
        </div></td>
        <td><div align="center" class="Style21">NOUS PERMET DE CONNAITRE LE NOMBRE DE PRODUIT COMMANDER PAR LES CLIENT </div></td>
        <td><div align="center" class="Style24">LES EMPLOYES QUI TRAVAILLE DANS LE SUPERMACH2 </div></td>
        <td><div align="center" class="Style22">IL NOUS DONNE DES INFORMATION SUR SA MARQUE, SON NOM,SON PRIX;;; </div></td>
        <td><div align="center" class="Style22">NOUS FOURNIE DES INFORMATIONS SUR LES DIFFERENTES CATEGORIES DE PRODUITS DISPONIBLES </div></td>
      </tr>
    </table>
  </div>
</form>

<p class="Style12"><span class="Style9"><span class="Style20"><span class="Style13"><span class="Style19"><a href="GESTION_CLIENTS.PHP" class="Style15 Style17">GESTIN_CLIENT</a></span></span><span class="Style19">&nbsp;<a href="GESTION_COMMANDES.PHP" class="Style15 Style17">GESTION_COMMANDDES</a> <span class="Style15 Style17"><a href="GESTION_EMPLOYES.PHP" class="Style18">GESTION_EMPLOYES </a> <a href="GESTION_PRODUITS.PHP" class="Style15 Style17">GESTION_PRODUIT</a></span> <a href="GESTION_RAYONS.PHP" class="Style15 Style17">GESTION_RAYONS </a> </span><span class="Style13">&nbsp;</span></p>
</body>
</html>